export const SET_OPERATION = 'SET_OPERATION';
export const APPEND_VALUE = 'APPEND_VALUE';
export const SET_OPERAND = 'SET_OPERAND';
export const EXECUTE_OPERATION = 'EXECUTE_OPERATION';
export const IMMEDIATE_EXECUTE = 'IMMEDIATE_EXECUTE';